services:
  mariadb:
    image: bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=daniel
      - MARIADB_DATABASE=wallamotop
    volumes:
      - mariadb_data:/bitnami/mariadb/data
    networks:
      - wallamotop_network
  #El contenedor de mariadb, se queda igual que el otro docker-compose (contenedor independiente)

#Este contenedor es el que sufre variación ya que es el que tiene nuestra imagen de laravel modificada con el proy
#Cambiamos la imagen.
#No hay volumenes, ni entrypoint.sh ni nada porque ya incluimos todo eso en la imagen de laravel personalizada en Dockerfile y la imagen que subimos al dockerhub
  
  wallamotop:
    container_name: wallamotop
    image: pdanielfg21/wallamotop-img  # tu imagen personalizada desde Docker Hub
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=daniel
      - DB_DATABASE=wallamotop
    depends_on:
      - mariadb
    networks:
      - wallamotop_network

#Imagen base sin modificar nuevamente, igual que le anterior docker-compose
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mariadb
      - MYSQL_USER=daniel
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    networks:
      - wallamotop_network

volumes:
  mariadb_data:

networks:
  wallamotop_network:
